#!/usr/bin/env python3
import json

with open('data/goodreadsData.json', 'r') as f:
    data = json.load(f)

patches = [
    # 4-star reads
    ("The Island", "McKinty", ["The Chain", "The Cold Cold Ground", "The Silent Patient", "Behind Closed Doors"]),
    ("The Rewind", "Scotch", ["Cleo McDougal Regrets Nothing", "The Insomniacs", "Romantic Comedy", "Normal People"]),
    ("You Have Arrived at Your Destination", "Towles", ["Recursion", "Dark Matter", "Summer Frost", "The Egg"]),
    ("Janesville", "Goldstein", ["Evicted", "Dopesick", "Methland", "Amity and Prosperity"]),
    ("Baseball Prospectus 2019", "Baseball Prospectus", ["The Extra 2%", "Trading Bases", "The Only Rule Is It Has to Work"]),
    ("Breaking Twitter", "Mezrich", ["The Accidental Billionaires", "Super Pumped", "Hatching Twitter", "Burn Book"]),
    ("The Midnight Ride", "Mezrich", ["The Accidental Billionaires", "Bitcoin Billionaires", "Checkmate", "Flash Crash"]),
    ("Astroball", "Reiter", ["The Extra 2%", "The Hot Hand", "The Only Rule Is It Has to Work", "The Midrange Theory"]),
    ("A Walk in the Woods", "Bryson", ["Into Thin Air", "The Lost City of the Monkey God", "The Wager", "A Short History of Nearly Everything"]),
    ("Summer Frost", "Crouch", ["Recursion", "Dark Matter", "The Egg", "You Have Arrived at Your Destination"]),
    ("Abandon", "Crouch", ["Desert Places", "Pines: Wayward Pines", "Recursion", "Dark Matter"]),
    ("Reagan", "Spitz", ["A Promised Land", "The Accidental President", "The Chief", "The Presidents Club"]),
    ("The Upstarts", "Stone", ["The Everything Store", "Amazon Unbound", "Super Pumped", "Hatching Twitter"]),
    ("Becoming Steve Jobs", "Schlender", ["Steve Jobs", "Elon Musk: Tesla", "The Everything Store", "Shoe Dog"]),
    ("LeBron, Inc.", "Windhorst", ["Return of the King", "Three-Ring Circus", "Dream Team", "A Hollywood Ending"]),
    ("The Woman in Me", "Spears", ["Me", "Not That Kind of Girl", "The Storyteller", "Born to Run"]),
    ("Born to Run", "Springsteen", ["Me", "The Storyteller", "A Life in Parts", "Yearbook"]),
    ("Good Morning, Monster", "Gildiner", ["Maybe You Should Talk to Someone", "When Breath Becomes Air", "Hidden Valley Road", "Educated"]),
    ("Chip War", "Miller", ["The Innovators", "Steve Jobs", "Elon Musk: Tesla", "AI Valley"]),
    ("The Space Barons", "Davenport", ["Elon Musk: Tesla", "When the Heavens Went on Sale", "Power Play: Tesla, Elon Musk, and the Bet of the Century", "The Everything Store"]),
    ("Eating the Dinosaur", "Klosterman", ["Sex, Drugs, and Cocoa Puffs", "I Wear the Black Hat", "The Nineties", "Downtown Owl"]),
    ("The Nineties", "Klosterman", ["Sex, Drugs, and Cocoa Puffs", "I Wear the Black Hat", "Eating the Dinosaur", "Downtown Owl"]),
    ("But What If We're Wrong", "Klosterman", ["Sex, Drugs, and Cocoa Puffs", "I Wear the Black Hat", "The Nineties", "Chuck Klosterman IV"]),
    ("The Scaling Curve", "St. John", ["Super Pumped", "Elon Musk: Tesla", "Empire of AI", "Steve Jobs"]),
    ("The Road", "McCarthy", ["The Postmortal", "World War Z", "Station Eleven", "The Stand"]),
    ("The Tomorrow Box", "Sittenfeld", ["Romantic Comedy", "Lessons in Chemistry", "One Day", "The Wedding People"]),
    ("Robin", "Itzkoff", ["A Life in Parts", "Me", "The Storyteller", "Yearbook"]),
    ("Us", "Nicholls", ["One Day", "Sweet Sorrow", "Normal People", "Good Material"]),
    ("Sweet Sorrow", "Nicholls", ["One Day", "Us", "Normal People", "Romantic Comedy"]),
    ("World According to Twitter", "Pogue", ["Hatching Twitter", "Super Pumped", "Things a Little Bird Told Me", "Burn Book"]),
    ("White Noise", "DeLillo", ["The Road", "Lake Success", "Normal People", "Beautiful World, Where Are You"]),
    ("Love by the Glass", "Gaiter", ["Cork Dork", "Save Me the Plums", "Eat a Peach", "Bourdain: The Definitive Oral Biography"]),
    ("The Lost City of the Monkey God", "Preston", ["Into Thin Air", "The Wager", "The Lost City of Z", "Diablo Mesa"]),
    ("The Night the Lights Went Out", "Magary", ["Someone Could Get Hurt", "The Glass Castle", "Educated", "Maid"]),
    ("Men with Balls", "Magary", ["Sex, Drugs, and Cocoa Puffs", "I Wear the Black Hat", "Yearbook", "The Hot Hand"]),
    ("Fresh Off the Boat", "Huang", ["Crying in H Mart", "Yes, Chef", "Eat a Peach", "Notes from a Young Black Chef"]),
    ("Buttermilk Graffiti", "Lee", ["Yes, Chef", "Eat a Peach", "Blood, Bones, and Butter", "L.A. Son"]),
    ("The Glass Hotel", "Mandel", ["Sea of Tranquility", "Station Eleven", "Exit Party", "The Silent Patient"]),
    ("Betaball", "Malinowski", ["Dream Team", "Three-Ring Circus", "Blood in the Garden", "The Extra 2%"]),
    ("My Seinfeld Year", "Stoller", ["Yearbook", "Born Standing Up", "A Life in Parts", "Comedy Comedy Comedy Drama"]),
    ("Another Day in the Death of America", "Younge", ["Evicted", "Dopesick", "The Glass Castle", "Maid"]),
    ("Netflixed", "Keating", ["That Will Never Work", "Super Pumped", "The Everything Store", "Hatching Twitter"]),
    ("The Holdout", "Moore", ["A Time to Kill", "The Firm", "The Client", "Presumed Innocent"]),
    ("Tell No One", "Coben", ["The Woods", "The Silent Patient", "Behind Closed Doors", "Say Nothing"]),
    ("Fool Me Once", "Coben", ["The Woods", "Tell No One", "The Silent Patient", "Say Nothing"]),
    ("Hillbilly Elegy", "Vance", ["Educated", "Maid", "The Glass Castle", "Heartland"]),
    ("Tokyo Vice", "Adelstein", ["American Kingpin", "The Art Thief", "Methland", "Inside the Cartel"]),
    ("Built to Lose", "Fischer", ["Dream Team", "Blood in the Garden", "Tanking to the Top", "Three-Ring Circus"]),
    ("Tiger Tiger", "Patterson", ["Along Came a Spider", "Kiss the Girls", "12 Months to Live", "The Jailhouse Lawyer"]),
    ("Jack & Jill (Alex Cross", "Patterson", ["Along Came a Spider", "Kiss the Girls", "Tiger Tiger", "12 Months to Live"]),
    ("Gandolfini", "Bailey", ["A Life in Parts", "Me", "Robin", "The Storyteller"]),
    ("Hidden Pictures", "Rekulak", ["The Last One at the Wedding", "The Silent Patient", "Behind Closed Doors", "The Outsider"]),
    ("The Arm", "Passan", ["The Extra 2%", "Trading Bases", "The Only Rule Is It Has to Work", "Charlie Hustle"]),
    ("You Shouldn't Have Come Here", "Rose", ["The Perfect Marriage", "The Perfect Divorce", "Home Is Where the Bodies Are", "Behind Closed Doors"]),
    ("The Anthropocene Reviewed", "Green", ["Turtles All the Way Down", "Looking for Alaska", "Paper Towns", "Everything Is Tuberculosis"]),
    ("Framed", "Grisham", ["The Innocent Man", "Just Mercy", "A Time to Kill", "Presumed Innocent"]),
    ("The Innocent Man", "Grisham", ["Framed", "Just Mercy", "A Time to Kill", "Under the Banner of Heaven"]),
    ("Sparring Partners", "Grisham", ["The Judge's List", "A Time to Kill", "The Firm", "Partners: A Rogue Lawyer Short Story"]),
    ("The Whistler (The Whistler, #1)", "Grisham", ["The Judge's List", "The Appeal", "The Rainmaker", "Partners: A Rogue Lawyer Short Story"]),
    ("Witness to a Trial", "Grisham", ["The Whistler", "A Time to Kill", "The Client", "Partners: A Rogue Lawyer Short Story"]),
    ("The Associate", "Grisham", ["The Firm", "The Street Lawyer", "The Rainmaker", "The French Illusion"]),
    ("Bleachers", "Grisham", ["Calico Joe", "Sooley", "Playing for Pizza", "The Boys from Biloxi"]),
    ("The Confession", "Grisham", ["A Time to Kill", "The Client", "The Firm", "Partners: A Rogue Lawyer Short Story"]),
    ("The Summons", "Grisham", ["The King of Torts", "The Partner", "The Rainmaker", "The French Illusion"]),
    ("The Brethren", "Grisham", ["The Partner", "The Firm", "The King of Torts", "The French Illusion"]),
    ("The Testament", "Grisham", ["The Broker", "The Firm", "The Partner", "The French Illusion"]),
    ("The Chamber", "Grisham", ["A Time to Kill", "The Client", "The Boys from Biloxi", "Partners: A Rogue Lawyer Short Story"]),
    ("The Pelican Brief", "Grisham", ["The Firm", "The Client", "A Time to Kill", "The French Illusion"]),
    ("The Rooster Bar", "Grisham", ["The Street Lawyer", "The Litigators", "The Rainmaker", "The French Illusion"]),
    ("The Appeal", "Grisham", ["The Whistler", "The Judge's List", "The Rainmaker", "Partners: A Rogue Lawyer Short Story"]),
    ("Camino Island (Camino Island, #1)", "Grisham", ["Camino Winds", "Camino Ghosts", "The Exchange", "The French Illusion"]),
    ("The Broker", "Grisham", ["The Partner", "The Firm", "The Exchange", "The French Illusion"]),
    ("Calico Joe", "Grisham", ["Bleachers", "Sooley", "Charlie Hustle", "The Boys from Biloxi"]),
    ("Rogue Lawyer (Rogue Lawyer, #1)", "Grisham", ["A Time to Kill", "The Client", "The Street Lawyer", "Partners: A Rogue Lawyer Short Story"]),
    ("Dark Angel (Letty Davenport", "Sandford", ["The Investigator", "Along Came a Spider", "The Chain", "Hard to Break"]),
    ("Up, Up, and Away", "Keri", ["The Extra 2%", "Trading Bases", "Charlie Hustle", "The Only Rule Is It Has to Work"]),
    ("Boys Among Men", "Jonathan Abrams", ["Dream Team", "Blood in the Garden", "Three-Ring Circus", "Giannis"]),
    ("Simplexity", "Kiley", ["Come and Get It", "Lessons in Chemistry", "Normal People", "Romantic Comedy"]),
    ("Talking as Fast as I Can", "Lauren Graham", ["Have I Told You This Already?", "In Conclusion, Don't Worry About It", "Not That Kind of Girl", "Bossypants"]),
    ("Nine Perfect Strangers", "Moriarty", ["Here One Moment", "The Husband's Secret", "Truly Madly Guilty", "The Silent Patient"]),
    ("Our Lady of Perpetual Hunger", "Donovan", ["Crying in H Mart", "Save Me the Plums", "Eat a Peach", "Blood, Bones, and Butter"]),
    ("Talking to Strangers", "Gladwell", ["The Tipping Point", "The Bomber Mafia", "Thinking, Fast and Slow", "Everybody Lies"]),
    ("How to Stop Time", "Haig", ["The Midnight Library", "The Midnight Train", "The Humans", "This Time Tomorrow"]),
    ("Greenlights", "McConaughey", ["A Life in Parts", "Me", "Born to Run", "Yearbook"]),
    ("The Premonition", "Michael   Lewis", ["The Big Short", "Flash Boys", "Dopesick", "The End of October"]),
    ("The Undoing Project", "Michael   Lewis", ["The Big Short", "Flash Boys", "Thinking, Fast and Slow", "Everybody Lies"]),
    ("Hard to Break", "Ledwidge", ["Run for Cover", "Stop at Nothing", "Dark Angel", "The Chain"]),
    ("Who Is Government", "Michael Lewis", ["The Premonition", "The Big Short", "Flash Boys", "Going Infinite"]),
    ("The Hanging Judge", "Ponsor", ["A Time to Kill", "Presumed Innocent", "The Last Trial", "The Client"]),
    ("The Soul of a Chef", "Ruhlman", ["The Making of a Chef", "Eat a Peach", "Yes, Chef", "If You Can't Take the Heat"]),
    ("Michael Symon's Live to Cook", "Symon", ["Eat a Peach", "Franklin Barbecue", "Yes, Chef", "Why I Cook"]),
    ("Digital Gold", "Popper", ["Bitcoin Billionaires", "Flash Boys", "The Trolls of Wall Street", "Going Infinite"]),
    ("Methland", "Reding", ["Dopesick", "Evicted", "American Overdose", "Janesville"]),
    ("The Maid (Molly the Maid, #1)", "Prose", ["The Mystery Guest", "The Maid's Secret", "The Mistletoe Mystery", "The Silent Patient"]),
    ("Clean Hands", "Patrick  Hoffman", ["Every Man a Menace", "The White Van", "She Rides Shotgun", "Everybody Knows"]),
    ("Every Man a Menace", "Patrick  Hoffman", ["Clean Hands", "The White Van", "She Rides Shotgun", "A Violent Masterpiece"]),
    ("The Girl on the Train", "Hawkins", ["A Slow Fire Burning", "Into the Water", "The Silent Patient", "Behind Closed Doors"]),
    ("The Ride of a Lifetime", "Iger", ["Shoe Dog", "The Everything Store", "Sam Walton", "What It Takes"]),
    ("Zero Days", "Ware", ["The Silent Patient", "Behind Closed Doors", "The Breakdown", "None of This Is True"]),
    ("Normal People", "Rooney", ["Beautiful World, Where Are You", "Intermezzo", "One Day", "Romantic Comedy"]),
    ("Sam Walton", "Walton", ["Shoe Dog", "The Ride of a Lifetime", "Built from Scratch", "The Everything Store"]),
    ("An Innocent Client", "Pratt", ["In Good Faith", "A Time to Kill", "The Client", "The Last Chance Lawyer"]),
    ("The Burden of Proof", "Turow", ["Presumed Innocent", "Pleading Guilty", "The Last Trial", "A Time to Kill"]),
    ("Black Edge", "Kolhatkar", ["Flash Boys", "The Big Short", "The Man Who Solved the Market", "Den of Thieves"]),
    ("The Elias Network", "Simon Gervais", ["The Blackbriar Genesis", "The Chain", "Along Came a Spider", "Dark Angel"]),
    ("While Justice Sleeps", "Stacey Abrams", ["Rogue Justice", "A Time to Kill", "The Client", "The Chief"]),
    ("The Long Walk", "Stephen  King", ["The Running Man", "The Postmortal", "World War Z", "The Stand"]),
    ("Rita Hayworth and Shawshank Redemption", "Stephen  King", ["The Body", "The Outsider", "Billy Summers", "A Face in the Crowd"]),
    ("The Institute", "Stephen  King", ["The Outsider", "Holly", "Mr. Mercedes", "Billy Summers"]),
    ("A Face in the Crowd", "Stephen  King", ["Rita Hayworth and Shawshank Redemption", "The Body", "The Outsider"]),
    ("Later", "Stephen  King", ["Holly", "The Outsider", "Billy Summers", "Mr. Mercedes"]),
    ("Worst Case Scenario", "Newman", ["Falling", "Drowning", "The Flight Attendant", "The Chain"]),
    ("Evidence of the Affair", "Taylor Jenkins Reid", ["Forever, Interrupted", "The Seven Husbands of Evelyn Hugo", "After I Do", "Romantic Comedy"]),
    ("Forever, Interrupted", "Taylor Jenkins Reid", ["Evidence of the Affair", "The Seven Husbands of Evelyn Hugo", "After I Do", "Lessons in Chemistry"]),
    ("Billion Dollar Whale", "Tom         Wright", ["Flash Boys", "The Big Short", "Going Infinite", "The Man Who Solved the Market"]),
    ("Think Like a Chef", "Colicchio", ["Why I Cook", "Eat a Peach", "Franklin Barbecue", "Yes, Chef"]),
    ("Me and Carlos", "Perrotta", ["Little Children", "Tracy Flick Can't Win", "Normal People", "Bad Haircut"]),
    ("Nine Inches", "Perrotta", ["Little Children", "Tracy Flick Can't Win", "Normal People", "Bad Haircut"]),
    ("The Abstinence Teacher", "Perrotta", ["Little Children", "Tracy Flick Can't Win", "Normal People", "Bad Haircut"]),
    ("Before the Coffee Gets Cold", "Kawaguchi", ["The Midnight Library", "How to Stop Time", "Recursion", "This Time Tomorrow"]),
    ("An Engineered Injustice", "Myers", ["A Criminal Defense", "A Killer's Alibi", "A Criminal Justice", "A Time to Kill"]),
    ("A Criminal Defense", "Myers", ["An Engineered Injustice", "A Killer's Alibi", "A Criminal Justice", "A Time to Kill"]),
    ("The Cost of These Dreams", "Thompson", ["Three-Ring Circus", "Tiger Woods", "Dream Team", "Pappyland"]),

    # 3-star reads
    ("Pledged", "Robbins", ["Educated", "Maid", "The Glass Castle", "A Hope in the Unseen"]),
    ("Unqualified", "Faris", ["Bossypants", "Sorry I'm Late", "Scrappy Little Nobody", "Not That Kind of Girl"]),
    ("Scrappy Little Nobody", "Kendrick", ["Bossypants", "Unqualified", "Sorry I'm Late", "Not That Kind of Girl"]),
    ("Demon Copperhead", "Kingsolver", ["Educated", "Maid", "Where the Crawdads Sing", "Dopesick"]),
    ("Baseball Between the Numbers", "Baseball Prospectus", ["The Extra 2%", "Trading Bases", "The Only Rule Is It Has to Work"]),
    ("Rigged", "Mezrich", ["The Accidental Billionaires", "Bitcoin Billionaires", "Flash Boys", "The Big Short"]),
    ("Cork Dork", "Bosker", ["Eat a Peach", "Save Me the Plums", "Blood, Bones, and Butter", "Get the Picture"]),
    ("Dirt", "Buford", ["Eat a Peach", "Blood, Bones, and Butter", "Yes, Chef", "Bourdain: The Definitive Oral Biography"]),
    ("Try Not to Suck", "Chastain", ["Charlie Hustle", "Tiger Woods", "Three-Ring Circus", "The Book of Joe"]),
    ("Desert Places", "Crouch", ["Abandon", "Pines: Wayward Pines", "Recursion", "Dark Matter"]),
    ("Ahead of the Curve", "Kenny", ["The Extra 2%", "Trading Bases", "The Hot Hand", "The Only Rule Is It Has to Work"]),
    ("Just Mercy", "Stevenson", ["Framed", "The Innocent Man", "A Time to Kill", "Under the Banner of Heaven"]),
    ("Our Missing Hearts", "Ng", ["Station Eleven", "Sea of Tranquility", "The Measure", "The Invisible Life of Addie LaRue"]),
    ("American Overdose", "McGreal", ["Dopesick", "Methland", "Evicted", "The Poisoned City"]),
    ("Born to Run", "McDougall", ["Into Thin Air", "Ghost Soldiers", "The Wager", "The Lost City of Z"]),
    ("The Big Payback", "Charnas", ["Jay-Z: Made in America", "The Storyteller", "Me", "Daisy Jones & The Six"]),
    ("Thinking, Fast and Slow", "Kahneman", ["The Tipping Point", "Talking to Strangers", "Everybody Lies", "Quiet"]),
    ("The Prophets of Smoked Meat", "Vaughn", ["Franklin Barbecue", "Blood, Bones, and Butter", "Eat a Peach", "Yes, Chef"]),
    ("Point B", "Magary", ["The Hike", "Recursion", "Dark Matter", "The Postmortal"]),
    ("The Hike", "Magary", ["Point B", "The Postmortal", "Dark Matter", "Recursion"]),
    ("Sea of Tranquility", "Mandel", ["Station Eleven", "The Glass Hotel", "Exit Party", "Last Night in Montreal"]),
    ("Station Eleven", "Mandel", ["Sea of Tranquility", "The Glass Hotel", "Exit Party", "The Road"]),
    ("Hardwood Paroxysm", "Hardwood Paroxysm", ["The Extra 2%", "Trading Bases", "Dream Team"]),
    ("Stay True", "Hsu", ["Crying in H Mart", "Educated", "Yearbook", "A Life in Parts"]),
    ("Ivan Ramen", "Orkin", ["Eat a Peach", "Blood, Bones, and Butter", "Yes, Chef", "L.A. Son"]),
    ("The Baseball Economist", "Bradbury", ["The Extra 2%", "Trading Bases", "The Hot Hand"]),
    ("Cat & Mouse (Alex Cross", "Patterson", ["Along Came a Spider", "Kiss the Girls", "12 Months to Live"]),
    ("Gunslinger", "Pearlman", ["Three-Ring Circus", "The Last Folk Hero", "Tiger Woods", "Boys Will Be Boys"]),
    ("My Next Breath", "Renner", ["A Life in Parts", "Me", "Robin", "Yearbook"]),
    ("The Founders", "Soni", ["Hatching Twitter", "Super Pumped", "The Everything Store", "The Accidental Billionaires"]),
    ("Business Adventures", "Brooks", ["Flash Boys", "The Big Short", "The Man Who Solved the Market", "Den of Thieves"]),
    ("The Guardians", "Grisham", ["A Time to Kill", "The Client", "Framed", "Partners: A Rogue Lawyer Short Story"]),
    ("Ford County", "Grisham", ["A Time to Kill", "The Boys from Biloxi", "Sparring Partners", "The French Illusion"]),
    ("Playing for Pizza", "Grisham", ["Bleachers", "Calico Joe", "Sooley", "The Boys from Biloxi"]),
    ("Skipping Christmas", "Grisham", ["Playing for Pizza", "Bleachers", "Calico Joe", "The French Illusion"]),
    ("A Painted House", "Grisham", ["The Boys from Biloxi", "Sycamore Row", "A Time to Kill", "The French Illusion"]),
    ("The Racketeer", "Grisham", ["The Firm", "A Time to Kill", "The Partner", "Partners: A Rogue Lawyer Short Story"]),
    ("The Marriage Act", "Marrs", ["The One", "The Family Experiment", "The Measure", "Recursion"]),
    ("All the Pieces Matter", "Jonathan Abrams", ["Boys Among Men", "Blood in the Garden", "Three-Ring Circus"]),
    ("2024: How Trump", "Dawsey", ["A Promised Land", "The Fifth Risk", "Careless People"]),
    ("The Optimist", "Hagey", ["Super Pumped", "Empire of AI", "Elon Musk: Tesla", "The Everything Store"]),
    ("Winning Fantasy Baseball", "Schechter", ["Trading Bases", "The Extra 2%", "The Only Rule Is It Has to Work"]),
    ("Shit, Actually", "West", ["Sex, Drugs, and Cocoa Puffs", "I Wear the Black Hat", "Yearbook", "The Wreckage of My Presence"]),
    ("Behind Closed Doors (Behind Closed Doors, #1)", "Lisa Renee Jones", ["Behind Closed Doors", "The Silent Patient", "Verity", "The Housemaid"]),
    ("The Tipping Point", "Malcolm Gladwell", ["Talking to Strangers", "The Bomber Mafia", "Thinking, Fast and Slow", "Everybody Lies"]),
    ("Dear Mr. You", "Parker", ["Not That Kind of Girl", "Stay True", "A Life in Parts", "Maid"]),
    ("Devolution", "Max Brooks", ["World War Z", "Tiger Chair", "The Postmortal", "The Stand"]),
    ("The Lost Story", "Shaffer", ["The Wishing Game", "The Storied Life of A.J. Fikry", "The Midnight Library", "Remarkably Bright Creatures"]),
    ("The Fifth Risk", "Michael   Lewis", ["The Premonition", "The Big Short", "Flash Boys", "The Undoing Project"]),
    ("Jay-Z", "Dyson", ["The Big Payback", "Daisy Jones & The Six", "The Storyteller", "Heartbreak Is the National Anthem"]),
    ("Smokin' with Myron Mixon", "Mixon", ["Franklin Barbecue", "Eat a Peach", "Blood, Bones, and Butter", "Yes, Chef"]),
    ("The Five Dysfunctions of a Team", "Lencioni", ["Shoe Dog", "The Ride of a Lifetime", "The Everything Store"]),
    ("Billion Dollar Loser", "Wiedeman", ["Super Pumped", "The Accidental Billionaires", "Hatching Twitter", "The Everything Store"]),
    ("Beautiful World, Where Are You", "Rooney", ["Normal People", "Intermezzo", "One Day", "Lessons in Chemistry"]),
    ("Boom Town", "Anderson", ["Evicted", "Chesapeake Requiem", "One Day: The Extraordinary Story", "Paradise"]),
    ("Heartland", "Smarsh", ["Educated", "Maid", "The Glass Castle", "Hillbilly Elegy"]),
    ("Five Days at Memorial", "Fink", ["Dopesick", "Evicted", "The Premonition", "Paradise"]),
    ("A Flicker in the Dark", "Willingham", ["The Silent Patient", "The Breakdown", "Behind Closed Doors", "A Slow Fire Burning"]),
    ("You Like It Darker", "King", ["Holly", "The Outsider", "Billy Summers", "Mr. Mercedes"]),
    ("Baseball Maverick", "Kettmann", ["The Extra 2%", "Charlie Hustle", "Three-Ring Circus", "Trading Bases"]),
    ("When to Rob a Bank", "Levitt", ["The Tipping Point", "Everybody Lies", "Thinking, Fast and Slow", "The Hot Hand"]),
    ("Quiet Power", "Cain", ["Quiet:", "Bittersweet", "Thinking, Fast and Slow", "Maybe You Should Talk to Someone"]),
    ("Quiet:", "Cain", ["Quiet Power", "Bittersweet", "Thinking, Fast and Slow", "Everybody Lies"]),
    ("Stories of Your Life and Others", "Chiang", ["Exhalation", "Recursion", "Dark Matter", "The Martian"]),

    # 2-star reads
    ("LIV and Let Die", "Shipnuck", ["Phil:", "Tiger Woods", "Charlie Hustle", "Open"]),
    ("The Poisoned City", "Clark", ["Dopesick", "Evicted", "American Overdose", "Amity and Prosperity"]),
    ("Bubbleball", "Golliver", ["Blood in the Garden", "Dream Team", "Inside the NBA Bubble", "Three-Ring Circus"]),
    ("The Lost Continent", "Bryson", ["A Walk in the Woods", "A Short History of Nearly Everything", "Into Thin Air"]),
    ("A Short History of Nearly Everything", "Bryson", ["A Walk in the Woods", "The Lost Continent", "Seeing Further"]),
    ("Dueling with Kings", "Barbarisi", ["Chasing the Thrill", "Trading Bases", "Everybody Lies", "You Can't Lose Them All"]),
    ("The Culture Code", "Coyle", ["Thinking, Fast and Slow", "The Tipping Point", "Talking to Strangers"]),
    ("Emotional Intelligence", "Goleman", ["Thinking, Fast and Slow", "Quiet:", "Maybe You Should Talk to Someone"]),
    ("The Rover", "Magary", ["The Postmortal", "Dark Matter", "Recursion", "Point B"]),
    ("My Name Is Lucy Barton", "Strout", ["Normal People", "Beautiful World, Where Are You", "Lessons in Chemistry"]),
    ("All Adults Here", "Straub", ["American Fantasy", "This Time Tomorrow", "Normal People", "Lessons in Chemistry"]),
    ("No More Tears", "Gardiner Harris", ["Dopesick", "Evicted", "The Secret Life of Groceries"]),
    ("There's Always This Year", "Abdurraqib", ["Blood in the Garden", "Dream Team", "Three-Ring Circus"]),
    ("Rickey", "Bryant", ["Tiger Woods", "The Last Folk Hero", "Charlie Hustle", "Sweetness"]),
    ("The Best American Food Writing", "López-Alt", ["Eat a Peach", "Blood, Bones, and Butter", "Yes, Chef"]),
    ("Invent and Wander", "Bezos", ["The Everything Store", "Amazon Unbound", "Shoe Dog", "Steve Jobs"]),
    ("The Nine", "Toobin", ["The Chief", "While Justice Sleeps", "A Time to Kill", "The Genome Defense"]),
    ("Sick in the Head", "Apatow", ["Yearbook", "Born Standing Up", "A Life in Parts", "Comedy Comedy Comedy Drama"]),
    ("I Regret Almost Everything", "McNally", ["Your Table Is Ready", "Eat a Peach", "Yes, Chef", "Save Me the Plums"]),
    ("How I Learned to Cook", "Witherspoon", ["Yes, Chef", "Eat a Peach", "Blood, Bones, and Butter"]),
    ("The Plague Year", "Lawrence Wright", ["Dopesick", "The Premonition", "The End of October", "Five Days at Memorial"]),
    ("The Three-Body Problem", "Cixin", ["Seveneves", "The Martian", "Recursion", "Children of Time"]),
    ("Can't Knock the Hustle", "Sullivan", ["Blood in the Garden", "Inside the NBA Bubble", "Dream Team"]),
    ("Poverty, by America", "Desmond", ["Evicted", "Maid", "Dopesick", "Amity and Prosperity"]),
    ("The Caesars Palace Coup", "Frumes", ["Flash Boys", "The Big Short", "Flash Crash", "Den of Thieves"]),
    ("The New New Thing", "Michael   Lewis", ["The Everything Store", "Super Pumped", "Hatching Twitter", "Steve Jobs"]),
    ("How to Be Perfect", "Schur", ["Big Fan", "Sex, Drugs, and Cocoa Puffs", "Yearbook", "I Wear the Black Hat"]),
    ("Emergency Skin", "Jemisin", ["The Egg", "Exhalation", "Recursion", "Dark Matter"]),
    ("A Slow Fire Burning", "Hawkins", ["The Girl on the Train", "Into the Water", "The Silent Patient", "A Flicker in the Dark"]),
    ("The Decline and Fall of IBM", "Cringely", ["The Innovators", "Steve Jobs", "Chip War", "AI Valley"]),
    ("No Filter", "Frier", ["Hatching Twitter", "Super Pumped", "The Everything Store", "Burn Book"]),
    ("American Kings", "Wickersham", ["Three-Ring Circus", "Boys Will Be Boys", "The Last Folk Hero", "Dream Team"]),
    ("Stories from the Tenants Downstairs", "Fofana", ["Normal People", "Maid", "Evicted", "Lessons in Chemistry"]),
    ("The Blackbriar Genesis", "Simon Gervais", ["The Elias Network", "The Chain", "Dark Angel", "Along Came a Spider"]),
    ("Fairy Tale", "Stephen  King", ["The Invisible Life of Addie LaRue", "The Stand", "The Road", "Recursion"]),
    ("Lorne", "Morrison", ["A Life in Parts", "Me", "The Storyteller", "Robin"]),
    ("The Library Book", "Orlean", ["The Art Thief", "The Secret Life of Groceries", "Evicted", "Chesapeake Requiem"]),
    ("Exhalation", "Chiang", ["Stories of Your Life and Others", "Recursion", "Dark Matter", "The Egg"]),

    # 1-star reads
    ("End of Story", "Finn", ["The Woman in the Window", "The Silent Patient", "Behind Closed Doors"]),
    ("The Pentagon's Brain", "Jacobsen", ["Nuclear War: A Scenario", "Ghost Soldiers", "The Arsenal of Democracy", "Unbroken"]),
    ("Hell of a Book", "Mott", ["Normal People", "Lessons in Chemistry", "Beautiful World, Where Are You"]),

    # 0-star (unrated) reads
    ("Once Upon a December", "Reichert", ["Romantic Comedy", "Lessons in Chemistry", "One Day", "The Wedding People"]),
    ("Seinfeldia", "Armstrong", ["Is This Anything?", "Parks and Rec", "Sex, Drugs, and Cocoa Puffs", "So Fetch"]),
    ("Gray Mountain", "Grisham", ["A Time to Kill", "The Client", "The Street Lawyer", "The French Illusion"]),
    ("Theodore Boone: Kid Lawyer", "Grisham", ["A Time to Kill", "The Client", "The Firm"]),
    ("The Abduction (Theodore Boone", "Grisham", ["Theodore Boone: Kid Lawyer", "A Time to Kill", "The Client"]),
    ("In Conclusion, Don't Worry About It", "Lauren Graham", ["Talking as Fast as I Can", "Have I Told You This Already?", "Bossypants"]),
    ("The Coming Storm", "Michael   Lewis", ["The Premonition", "The Fifth Risk", "Flash Boys", "Going Infinite"]),
    ("Next: The Future Just Happened", "Michael   Lewis", ["The New New Thing", "The Innovators", "Super Pumped", "Hatching Twitter"]),
    ("Liar's Poker", "Michael   Lewis", ["Flash Boys", "The Big Short", "Going Infinite", "Den of Thieves"]),
    ("Meat", "LaFrieda", ["Franklin Barbecue", "Eat a Peach", "Yes, Chef", "Blood, Bones, and Butter"]),

    # Currently-reading
    ("In Good Faith", "Pratt", ["An Innocent Client", "A Time to Kill", "The Client", "The Last Chance Lawyer"]),
]

updated = 0
unmatched = []

for title_frag, author_frag, similar in patches:
    matches = [b for b in data['books']
               if title_frag.lower() in b.get('title', '').lower()
               and author_frag.lower() in b.get('author', '').lower()]
    if not matches:
        unmatched.append((title_frag, author_frag))
        continue
    for book in matches:
        if not book.get('similarToTitles') or len(book.get('similarToTitles', [])) == 0:
            book['similarToTitles'] = similar
            updated += 1

with open('data/goodreadsData.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated: {updated} books")
if unmatched:
    print(f"Unmatched ({len(unmatched)}):")
    for t, a in unmatched:
        print(f"  '{t}' / '{a}'")
else:
    print("All patches matched.")
