#!/usr/bin/env python3
import json

with open('data/goodreadsData.json', 'r') as f:
    data = json.load(f)

patches = [
    # 4-star reads
    ("The Island", "McKinty", ["thriller", "crime", "suspense"]),
    ("The Rewind", "Scotch", ["contemporary", "literary", "romance"]),
    ("You Have Arrived at Your Destination", "Towles", ["speculative", "sci-fi"]),
    ("Janesville", "Goldstein", ["narrative nonfiction", "political", "history"]),
    ("Baseball Prospectus 2019", "Baseball Prospectus", ["sports"]),
    ("Breaking Twitter", "Mezrich", ["tech history", "narrative nonfiction"]),
    ("The Midnight Ride", "Mezrich", ["thriller", "historical", "adventure"]),
    ("Astroball", "Reiter", ["sports", "narrative nonfiction"]),
    ("A Walk in the Woods", "Bryson", ["humor", "narrative nonfiction", "adventure"]),
    ("Summer Frost", "Crouch", ["speculative", "sci-fi"]),
    ("Abandon", "Crouch", ["thriller", "mystery", "crime"]),
    ("Reagan", "Spitz", ["biography", "political", "history"]),
    ("The Upstarts", "Stone", ["tech history", "business", "narrative nonfiction"]),
    ("Becoming Steve Jobs", "Schlender", ["biography", "tech history", "business"]),
    ("LeBron, Inc.", "Windhorst", ["sports", "biography", "business"]),
    ("The Woman in Me", "Spears", ["memoir", "biography"]),
    ("Born to Run", "Springsteen", ["memoir", "music history"]),
    ("Good Morning, Monster", "Gildiner", ["memoir", "psychology", "narrative nonfiction"]),
    ("Chip War", "Miller", ["tech history", "narrative nonfiction", "history"]),
    ("The Space Barons", "Davenport", ["tech history", "narrative nonfiction"]),
    ("Eating the Dinosaur", "Klosterman", ["humor", "narrative nonfiction", "sports"]),
    ("The Nineties", "Klosterman", ["history", "narrative nonfiction", "humor"]),
    ("But What If We're Wrong", "Klosterman", ["narrative nonfiction", "humor"]),
    ("The Scaling Curve", "St. John", ["tech history", "narrative nonfiction"]),
    ("The Road", "McCarthy", ["literary", "speculative", "adventure"]),
    ("The Tomorrow Box", "Sittenfeld", ["literary", "contemporary"]),
    ("Robin", "Itzkoff", ["biography", "memoir"]),
    ("Us", "Nicholls", ["literary", "contemporary", "romance"]),
    ("Sweet Sorrow", "Nicholls", ["literary", "contemporary", "romance"]),
    ("World According to Twitter", "Pogue", ["tech history", "humor"]),
    ("White Noise", "DeLillo", ["literary", "speculative", "social commentary"]),
    ("Love by the Glass", "Gaiter", ["memoir", "food"]),
    ("The Lost City of the Monkey God", "Preston", ["narrative nonfiction", "adventure"]),
    ("The Night the Lights Went Out", "Magary", ["memoir", "narrative nonfiction"]),
    ("Men with Balls", "Magary", ["humor", "sports"]),
    ("Fresh Off the Boat", "Huang", ["memoir", "food"]),
    ("Buttermilk Graffiti", "Lee", ["food", "narrative nonfiction"]),
    ("The Glass Hotel", "Mandel", ["literary", "mystery", "speculative"]),
    ("Betaball", "Malinowski", ["sports", "tech history", "narrative nonfiction"]),
    ("My Seinfeld Year", "Stoller", ["humor", "memoir"]),
    ("Another Day in the Death of America", "Younge", ["narrative nonfiction", "political"]),
    ("Netflixed", "Keating", ["business", "tech history", "narrative nonfiction"]),
    ("The Holdout", "Moore", ["legal", "thriller", "courtroom"]),
    ("Tell No One", "Coben", ["thriller", "mystery", "suspense"]),
    ("Fool Me Once", "Coben", ["thriller", "mystery", "suspense"]),
    ("Hillbilly Elegy", "Vance", ["memoir", "political", "narrative nonfiction"]),
    ("Tokyo Vice", "Adelstein", ["crime", "narrative nonfiction", "thriller"]),
    ("Built to Lose", "Fischer", ["sports", "business", "narrative nonfiction"]),
    ("Tiger Tiger", "Patterson", ["thriller", "crime"]),
    ("Jack & Jill", "Patterson", ["thriller", "crime"]),
    ("Gandolfini", "Bailey", ["biography", "memoir"]),
    ("Hidden Pictures", "Rekulak", ["thriller", "mystery", "horror"]),
    ("The Arm", "Passan", ["sports", "narrative nonfiction"]),
    ("You Shouldn't Have Come Here", "Rose", ["thriller", "horror", "suspense"]),
    ("The Anthropocene Reviewed", "Green", ["memoir", "narrative nonfiction"]),
    ("Framed", "Grisham", ["true crime", "legal", "narrative nonfiction"]),
    ("The Innocent Man", "Grisham", ["true crime", "legal", "narrative nonfiction"]),
    ("Sparring Partners", "Grisham", ["legal", "thriller", "courtroom"]),
    ("The Whistler", "Grisham", ["legal", "thriller", "courtroom"]),
    ("Witness to a Trial", "Grisham", ["legal", "thriller", "courtroom"]),
    ("The Associate", "Grisham", ["legal", "thriller", "courtroom"]),
    ("Bleachers", "Grisham", ["literary", "sports"]),
    ("The Confession", "Grisham", ["legal", "thriller", "courtroom"]),
    ("The Summons", "Grisham", ["legal", "thriller", "courtroom"]),
    ("The Brethren", "Grisham", ["legal", "thriller", "courtroom"]),
    ("The Testament", "Grisham", ["legal", "thriller", "adventure"]),
    ("The Chamber", "Grisham", ["legal", "courtroom", "crime"]),
    ("The Pelican Brief", "Grisham", ["legal", "thriller", "political"]),
    ("The Rooster Bar", "Grisham", ["legal", "thriller", "contemporary"]),
    ("The Appeal", "Grisham", ["legal", "political", "thriller"]),
    ("Camino Island", "Grisham", ["thriller", "mystery", "contemporary"]),
    ("The Broker", "Grisham", ["thriller", "political", "adventure"]),
    ("Calico Joe", "Grisham", ["sports", "literary"]),
    ("Rogue Lawyer", "Grisham", ["legal", "thriller", "crime"]),
    ("Dark Angel", "Sandford", ["thriller", "crime", "suspense"]),
    ("Up, Up, and Away", "Keri", ["sports", "narrative nonfiction"]),
    ("Boys Among Men", "Jonathan Abrams", ["sports", "narrative nonfiction"]),
    ("Simplexity", "Kiley", ["literary", "contemporary", "social commentary"]),
    ("Talking as Fast as I Can", "Lauren Graham", ["memoir", "humor"]),
    ("Nine Perfect Strangers", "Moriarty", ["thriller", "suspense", "contemporary"]),
    ("Our Lady of Perpetual Hunger", "Donovan", ["memoir", "food"]),
    ("Talking to Strangers", "Gladwell", ["narrative nonfiction", "psychology"]),
    ("How to Stop Time", "Haig", ["speculative", "literary", "contemporary"]),
    ("Greenlights", "McConaughey", ["memoir", "biography"]),
    ("The Premonition", "Lewis", ["narrative nonfiction", "political"]),
    ("The Undoing Project", "Lewis", ["narrative nonfiction", "psychology"]),
    ("Hard to Break", "Ledwidge", ["thriller", "crime", "suspense"]),
    ("Who Is Government", "Lewis", ["narrative nonfiction", "political"]),
    ("The Hanging Judge", "Ponsor", ["legal", "thriller", "courtroom"]),
    ("The Soul of a Chef", "Ruhlman", ["food", "narrative nonfiction"]),
    ("Michael Symon's Live to Cook", "Symon", ["food"]),
    ("Digital Gold", "Popper", ["finance", "tech history", "narrative nonfiction"]),
    ("Methland", "Reding", ["narrative nonfiction", "crime", "true crime"]),
    ("The Maid", "Prose", ["mystery", "thriller", "contemporary"]),
    ("Clean Hands", "Hoffman", ["thriller", "crime", "noir"]),
    ("Every Man a Menace", "Hoffman", ["thriller", "crime", "noir"]),
    ("The Girl on the Train", "Hawkins", ["thriller", "mystery", "psychological", "domestic suspense"]),
    ("The Ride of a Lifetime", "Iger", ["business", "memoir", "biography"]),
    ("Zero Days", "Ware", ["thriller", "mystery", "suspense"]),
    ("Normal People", "Rooney", ["literary", "contemporary", "romance"]),
    ("Sam Walton", "Walton", ["business", "biography", "memoir"]),
    ("An Innocent Client", "Pratt", ["legal", "thriller", "courtroom"]),
    ("The Burden of Proof", "Turow", ["legal", "thriller", "courtroom"]),
    ("Black Edge", "Kolhatkar", ["narrative nonfiction", "finance", "crime"]),
    ("The Elias Network", "Gervais", ["thriller", "spy", "suspense"]),
    ("While Justice Sleeps", "Stacey Abrams", ["legal", "thriller", "political"]),
    ("The Long Walk", "King", ["speculative", "horror", "suspense"]),
    ("Rita Hayworth and Shawshank Redemption", "King", ["literary", "crime"]),
    ("The Institute", "King", ["thriller", "horror", "speculative"]),
    ("A Face in the Crowd", "King", ["horror", "literary"]),
    ("Later", "King", ["thriller", "horror", "speculative"]),
    ("If It Bleeds", "King", ["thriller", "horror"]),
    ("Worst Case Scenario", "Newman", ["thriller", "suspense", "high-concept"]),
    ("Evidence of the Affair", "Taylor Jenkins Reid", ["contemporary", "romance"]),
    ("Forever, Interrupted", "Taylor Jenkins Reid", ["contemporary", "romance", "literary"]),
    ("Billion Dollar Whale", "Wright", ["narrative nonfiction", "finance", "crime"]),
    ("Think Like a Chef", "Colicchio", ["food"]),
    ("Me and Carlos", "Perrotta", ["literary", "contemporary"]),
    ("Nine Inches", "Perrotta", ["literary", "contemporary"]),
    ("The Abstinence Teacher", "Perrotta", ["literary", "contemporary"]),
    ("Before the Coffee Gets Cold", "Kawaguchi", ["speculative", "literary", "contemporary"]),
    ("An Engineered Injustice", "Myers", ["legal", "thriller", "courtroom"]),
    ("A Criminal Defense", "Myers", ["legal", "thriller", "courtroom"]),
    ("The Cost of These Dreams", "Thompson", ["sports", "narrative nonfiction"]),

    # 3-star reads
    ("Pledged", "Robbins", ["narrative nonfiction", "social commentary"]),
    ("Unqualified", "Faris", ["memoir", "humor"]),
    ("Scrappy Little Nobody", "Kendrick", ["memoir", "humor"]),
    ("Demon Copperhead", "Kingsolver", ["literary", "contemporary", "social commentary"]),
    ("Baseball Between the Numbers", "Baseball Prospectus", ["sports"]),
    ("Rigged", "Mezrich", ["narrative nonfiction", "finance", "adventure"]),
    ("Cork Dork", "Bosker", ["food", "narrative nonfiction"]),
    ("Dirt", "Buford", ["food", "memoir"]),
    ("Try Not to Suck", "Chastain", ["sports", "biography"]),
    ("Desert Places", "Crouch", ["thriller", "horror", "crime"]),
    ("Ahead of the Curve", "Kenny", ["sports", "narrative nonfiction"]),
    ("Just Mercy", "Stevenson", ["narrative nonfiction", "legal", "true crime"]),
    ("Our Missing Hearts", "Ng", ["speculative", "literary", "social commentary"]),
    ("American Overdose", "McGreal", ["narrative nonfiction", "true crime"]),
    ("Born to Run", "McDougall", ["narrative nonfiction", "sports", "adventure"]),
    ("The Big Payback", "Charnas", ["music history", "narrative nonfiction"]),
    ("Thinking, Fast and Slow", "Kahneman", ["psychology", "narrative nonfiction"]),
    ("The Prophets of Smoked Meat", "Vaughn", ["food", "narrative nonfiction"]),
    ("Someday", "Levithan", ["YA", "speculative", "contemporary"]),
    ("Point B", "Magary", ["speculative", "humor"]),
    ("The Hike", "Magary", ["speculative", "adventure", "humor"]),
    ("Sea of Tranquility", "Mandel", ["speculative", "literary"]),
    ("Station Eleven", "Mandel", ["speculative", "literary"]),
    ("Hardwood Paroxysm", "Hardwood Paroxysm", ["sports"]),
    ("Stay True", "Hsu", ["memoir", "literary"]),
    ("Ivan Ramen", "Orkin", ["food", "memoir"]),
    ("The Baseball Economist", "Bradbury", ["sports"]),
    ("Cat & Mouse", "Patterson", ["thriller", "crime"]),
    ("Gunslinger", "Pearlman", ["sports", "biography"]),
    ("My Next Breath", "Renner", ["memoir", "biography"]),
    ("The Founders", "Soni", ["tech history", "biography", "narrative nonfiction"]),
    ("Business Adventures", "Brooks", ["finance", "narrative nonfiction", "business"]),
    ("The Guardians", "Grisham", ["legal", "thriller", "courtroom"]),
    ("Ford County", "Grisham", ["legal", "literary"]),
    ("Playing for Pizza", "Grisham", ["sports", "contemporary"]),
    ("Skipping Christmas", "Grisham", ["humor", "contemporary"]),
    ("A Painted House", "Grisham", ["literary", "historical"]),
    ("The Racketeer", "Grisham", ["legal", "thriller", "crime"]),
    ("The Marriage Act", "Marrs", ["speculative", "thriller"]),
    ("All the Pieces Matter", "Jonathan Abrams", ["narrative nonfiction"]),
    ("2024: How Trump", "Dawsey", ["political", "narrative nonfiction"]),
    ("The Optimist", "Hagey", ["tech history", "biography", "narrative nonfiction"]),
    ("Winning Fantasy Baseball", "Schechter", ["sports"]),
    ("Shit, Actually", "West", ["humor"]),
    ("Behind Closed Doors", "Jones", ["thriller", "romance", "contemporary"]),
    ("The Tipping Point", "Gladwell", ["narrative nonfiction", "psychology", "business"]),
    ("Dear Mr. You", "Parker", ["memoir", "literary"]),
    ("Devolution", "Max Brooks", ["thriller", "horror", "speculative"]),
    ("The Lost Story", "Shaffer", ["contemporary", "literary", "romance"]),
    ("The Fifth Risk", "Lewis", ["narrative nonfiction", "political"]),
    ("Jay-Z", "Dyson", ["music history", "biography"]),
    ("Smokin' with Myron Mixon", "Mixon", ["food"]),
    ("The Five Dysfunctions of a Team", "Lencioni", ["business"]),
    ("Billion Dollar Loser", "Wiedeman", ["business", "narrative nonfiction"]),
    ("Beautiful World, Where Are You", "Rooney", ["literary", "contemporary"]),
    ("Boom Town", "Anderson", ["narrative nonfiction", "sports", "history"]),
    ("Heartland", "Smarsh", ["memoir", "narrative nonfiction"]),
    ("Five Days at Memorial", "Fink", ["narrative nonfiction", "true crime"]),
    ("A Flicker in the Dark", "Willingham", ["thriller", "mystery", "psychological"]),
    ("You Like It Darker", "King", ["thriller", "horror"]),
    ("Baseball Maverick", "Kettmann", ["sports", "biography"]),
    ("When to Rob a Bank", "Levitt", ["narrative nonfiction", "humor"]),
    ("Quiet Power", "Cain", ["psychology", "narrative nonfiction"]),
    ("Quiet:", "Cain", ["psychology", "narrative nonfiction"]),
    ("Stories of Your Life and Others", "Chiang", ["speculative", "sci-fi", "literary"]),

    # 2-star reads
    ("LIV and Let Die", "Shipnuck", ["sports", "narrative nonfiction"]),
    ("The Poisoned City", "Clark", ["narrative nonfiction", "political"]),
    ("Bubbleball", "Golliver", ["sports", "narrative nonfiction"]),
    ("The Lost Continent", "Bryson", ["humor", "narrative nonfiction", "adventure"]),
    ("A Short History of Nearly Everything", "Bryson", ["narrative nonfiction", "history"]),
    ("Dueling with Kings", "Barbarisi", ["sports", "narrative nonfiction"]),
    ("The Culture Code", "Coyle", ["business", "psychology"]),
    ("Emotional Intelligence", "Goleman", ["psychology"]),
    ("The Rover", "Magary", ["speculative", "sci-fi", "adventure"]),
    ("My Name Is Lucy Barton", "Strout", ["literary", "contemporary"]),
    ("All Adults Here", "Straub", ["literary", "contemporary"]),
    ("No More Tears", "Gardiner Harris", ["narrative nonfiction", "business"]),
    ("There's Always This Year", "Abdurraqib", ["memoir", "sports", "literary"]),
    ("Rickey", "Bryant", ["biography", "sports", "narrative nonfiction"]),
    ("The Best American Food Writing", "López-Alt", ["food"]),
    ("Invent and Wander", "Bezos", ["business", "memoir"]),
    ("The Nine", "Toobin", ["legal", "narrative nonfiction"]),
    ("Sick in the Head", "Apatow", ["humor", "memoir"]),
    ("I Regret Almost Everything", "McNally", ["memoir", "food"]),
    ("How I Learned to Cook", "Witherspoon", ["food"]),
    ("The Plague Year", "Lawrence Wright", ["narrative nonfiction", "true crime"]),
    ("The Three-Body Problem", "Cixin", ["sci-fi", "speculative"]),
    ("Can't Knock the Hustle", "Sullivan", ["sports", "narrative nonfiction"]),
    ("Poverty, by America", "Desmond", ["narrative nonfiction", "political", "social commentary"]),
    ("The Caesars Palace Coup", "Frumes", ["narrative nonfiction", "finance", "business"]),
    ("The New New Thing", "Lewis", ["tech history", "narrative nonfiction"]),
    ("How to Be Perfect", "Schur", ["humor"]),
    ("Emergency Skin", "Jemisin", ["speculative", "sci-fi"]),
    ("A Slow Fire Burning", "Hawkins", ["thriller", "mystery", "psychological"]),
    ("The Decline and Fall of IBM", "Cringely", ["tech history", "business"]),
    ("No Filter", "Frier", ["tech history", "narrative nonfiction", "business"]),
    ("American Kings", "Wickersham", ["sports", "narrative nonfiction"]),
    ("Stories from the Tenants Downstairs", "Fofana", ["literary", "contemporary"]),
    ("The Blackbriar Genesis", "Gervais", ["thriller", "spy"]),
    ("Fairy Tale", "King", ["speculative", "literary", "adventure"]),
    ("Lorne", "Morrison", ["biography", "memoir"]),
    ("The Library Book", "Orlean", ["narrative nonfiction", "literary"]),
    ("Exhalation", "Chiang", ["speculative", "sci-fi"]),

    # 1-star reads
    ("End of Story", "Finn", ["thriller", "psychological"]),
    ("The Pentagon's Brain", "Jacobsen", ["narrative nonfiction", "military", "history"]),
    ("Hell of a Book", "Mott", ["literary", "contemporary"]),

    # 0-star (unrated) reads
    ("Once Upon a December", "Reichert", ["contemporary", "romance"]),
    ("Seinfeldia", "Armstrong", ["narrative nonfiction", "humor"]),
    ("Gray Mountain", "Grisham", ["legal", "thriller", "contemporary"]),
    ("Theodore Boone: Kid Lawyer", "Grisham", ["legal", "YA"]),
    ("The Abduction", "Grisham", ["legal", "YA"]),
    ("In Conclusion, Don't Worry About It", "Lauren Graham", ["memoir", "humor"]),
    ("The Coming Storm", "Lewis", ["narrative nonfiction", "political"]),
    ("Next: The Future Just Happened", "Lewis", ["tech history", "narrative nonfiction"]),
    ("Liar's Poker", "Lewis", ["finance", "narrative nonfiction"]),
    ("Meat", "LaFrieda", ["food"]),

    # Currently-reading
    ("In Good Faith", "Pratt", ["legal", "thriller", "courtroom"]),
]

updated = 0
unmatched = []

for title_frag, author_frag, themes in patches:
    matches = [b for b in data['books']
               if title_frag.lower() in b.get('title', '').lower()
               and author_frag.lower() in b.get('author', '').lower()]
    if not matches:
        unmatched.append((title_frag, author_frag))
        continue
    for book in matches:
        if not book.get('themes') or len(book.get('themes', [])) == 0:
            book['themes'] = themes
            updated += 1

with open('data/goodreadsData.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated: {updated} books")
if unmatched:
    print(f"Unmatched ({len(unmatched)}):")
    for t, a in unmatched:
        print(f"  '{t}' / '{a}'")
else:
    print("All patches matched.")
